[build]
  publish = "public"
  command = "yarn build"
  functions = "lambda"

[build.environment]
  YARN_VERSION = "1.21.1"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/admin"
  to = "https://cms.starterstorm.com/wp-login.php"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 301

[[redirects]]
  from = "/discord"
  to = "/api/discord/invite"
  status = 301